src/BlogItium/urls.py
from django.contrib import admin
from django.urls import path, include
from publication.views import accueil_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('publication.urls')),
    path('', accueil_page, name="accueil")
]

src/publication/urls.py
from django.urls import path
from publication.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete


app_name = "posts"
urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name="edit"),
    path('<str:slug>/', BlogPostDetail.as_view(), name="post"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
]

src/publication/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse


User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    
    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"
        
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        
        if not self.slug:
            self.slug = slugify(self.title)
        
        super().save(*args, **kwargs)   
        
    @property
    def author_or_default(self):
        if self.author:
            return self.author.username
        return "Auteur inconnu"
    
    def get_absolute_url(self):
        return reverse('posts:home')

src/publication/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from publication.models import BlogPost
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def accueil_page(request):
    return render(request, "accueil.html")

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"
    template_name = "posts/blogpost_all.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        
        return queryset.filter(published=True)
    

@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title', 'content', 'published', 'author', ]
    
    
@method_decorator(login_required, name='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_update.html"
    fields = ['title', 'content', 'published', 'author', ]


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"
    template_name = "posts/blogpost_detail.html"
    
    
@method_decorator(login_required, name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = "posts/blogpost_delete.html"
    context_object_name = "post"
    success_url = reverse_lazy("posts:home")

src/publication/templates/posts/blogpost_all.html
{% extends 'base.html' %}

{% block title %}
    <title> Accueil de BlogItium </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

    <h2 style="text-decoration:underline;"> Voici Nos Articles : </h2>

    {% for post in posts %}
    <div class="main_all_article">
        <article class="txt_article">
            <h3> {{post.title}} </h3>
            <h5> Publié par <i> {{post.author_or_default}} </i> le {{post.created_on}} </h5>
            <p> {{post.content|safe|truncatewords:30}} </p>
        </article>

        <form action="{% url 'posts:post' slug=post.slug %}">
            <button class="btn_read"> Lire l'article </button>
        </form>
        
        {% if request.user.is_authenticated %}
            <div class="all_btn">
                <a class="btn" href="{% url 'posts:edit' slug=post.slug %}"> Modifier </a>
                <a class="btn" href="{% url 'posts:delete' slug=post.slug %}"> Supprimer </a>
            </div>
        {% endif %}
    </div>

    {% endfor %}

{% endblock %}

src/publication/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title> Créer un Article </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

    <h2 style="text-decoration:underline;"> Ajouter un Article </h2>

    <form method="POST" class="txt_article">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn" type="submit" value="Créer">
    </form>

{% endblock %}

src/publication/templates/posts/blogpost_delete.html
{% extends 'base.html' %}

{% block title %}
    <title> Suppression de l'article {{post.title}} </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

        <form method="POST" class="txt_article">
            {% csrf_token %}
            <p style="text-decoration:underline;"> Voulez-vous supprimer {{post.title}} ? </p>
            <input class="btn" type="submit" value="Supprimer">
        </form>

{% endblock %}

src/publication/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title> Article {{post.title}} </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

    <article class="txt_article">
        <h2> {{post.title}} </h2>
        <p> {{post.content|safe}} </p>
    </article>

{% endblock %}

src/publication/templates/posts/blogpost_update.html
{% extends 'base.html' %}

{% block title %}
    <title> Modifier un Article </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

    <h2 style="text-decoration:underline;"> Modification d'un Article </h2>

    <form method="POST" class="txt_article">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn" type="submit" value="Modifier">
    </form>

{% endblock %}

src/templates/accueil.html
{% extends 'base.html' %}

{% block title %}
    <title> Accueil de BlogItium </title>
{% endblock %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/head&foot.css' %}">

    <img class="img_main" src="{% static 'ressources/main_img.png' %}">

        <h2 style="text-decoration:underline;"> Bienvenue sur le Blog d'Initium ! </h2>

        <div class="accueil_txt">
            <h4> Technologie et Informatique sont des sujets qui sont évoqués dans nos articles ! </h4>
            <p> Nous mettons un point d'honneur quant à la diffusion d'information vérifié et correcte. 
                Nous souhaitons transmettre le savoir et éduquer sur les progrès technologiques, ainsi qu'expliquer leurs fonctionnements.    
            </p>    
        </div>

{% endblock %}

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'ressources/icon_site.png' %}">
    {% block title %} <title> Page par défaut </title> {% endblock %}
    <link rel="stylesheet" href="{% static 'css/head&foot.css' %}">
</head>
<body>
    <header>
        <h1> BlogItium </h1>

        <nav>
            <a class="nav_txt" href="{% url 'accueil' %}"> Accueil </a>
            <a class="nav_txt" href="{% url 'posts:home' %}"> Articles </a>
            {% if request.user.is_authenticated %}
                <a class="nav_txt" href="{% url 'posts:create' %}"> Créer un Article </a>
            {% endif %}
        </nav>
    </header>

    <section class="main_content">
        {% block main %}

        {% endblock %}
    </section>

    <footer>
        <span> Retrouvez moi sur : <a style="color:black;" href="https://twitter.com/home" target="_blank"> Twitter </a> </span>
        <span> Retrouvez moi sur : <a style="color:black;" href="https://www.youtube.com/c/Initium0_0/videos" target="_blank"> YouTube </a> </span>
        <span> Retrouvez moi sur : <a style="color:black;" href="https://www.instagram.com/real_initium/" target="_blank"> Instagram </a> </span>
    </footer>
</body>
</html>